const handshakeUniversities = {
  "Alabama A&M University": "aamu.joinhandshake.com",
  "Abilene Christian University": "acu.joinhandshake.com",
  "Adelphi University": "adelphi.joinhandshake.com",
  "Adrian College": "adrian.joinhandshake.com",
  "Agnes Scott College": "agnesscott.joinhandshake.com",
  "University of Akron": "akron.joinhandshake.com",
  "Alamo Colleges": "alamo.joinhandshake.com",
  "Alabama State University": "alasu.joinhandshake.com",
  "University at Albany": "albany.joinhandshake.com",
  "Albion College": "albion.joinhandshake.com",
  "Albright College": "albright.joinhandshake.com",
  "Alcorn State University": "alcorn.joinhandshake.com",
  "Alfred University": "alfred.joinhandshake.com",
  "Alfred State": "alfredstate.joinhandshake.com",
  "Allen University": "allenuniversity.joinhandshake.com",
  "Alma College": "alma.joinhandshake.com",
  "Alvernia University": "alvernia.joinhandshake.com",
  "American University": "american.joinhandshake.com",
  "Anderson University": "anderson.joinhandshake.com",
  "Andrews University": "andrews.joinhandshake.com",
  "Angelo State University": "angelo.joinhandshake.com",
  "Appalachian State University": "appstate.joinhandshake.com",
  "Azusa Pacific University": "apu.joinhandshake.com",
  "Aquinas College": "aquinas.joinhandshake.com",
  "Spring Arbor University": "arbor.joinhandshake.com",
  "Arcadia University": "arcadia.joinhandshake.com",
  "University of Arizona": "arizona.joinhandshake.com",
  "Arkansas Baptist College": "arkansasbaptist.joinhandshake.com",
  "Arizona State University": "asu.joinhandshake.com",
  "Albany State University": "asurams.joinhandshake.com",
  "Atlantic Cape Community College": "atlantic.joinhandshake.com",
  "Auburn University": "auburn.joinhandshake.com",
  "Augustana University": "augustana.joinhandshake.com",
  "Austin Community College": "austincc.joinhandshake.com",
  "Baker College": "baker.joinhandshake.com",
  "Bard College": "bard.joinhandshake.com",
  "Baruch College": "baruch.joinhandshake.com",
  "Bates College": "bates.joinhandshake.com",
  "Baylor University": "baylor.joinhandshake.com",
  "Boston College": "bc.joinhandshake.com",
  "Bronx Community College": "bcc.joinhandshake.com",
  "Belmont University": "belmont.joinhandshake.com",
  "Benedict College": "benedict.joinhandshake.com",
  "Bennett College": "bennett.joinhandshake.com",
  "Bergen Community College": "bergen.joinhandshake.com",
  "University of California Berkeley": "berkeley.joinhandshake.com",
  "Berry College": "berry.joinhandshake.com",
  "Bowling Green State University": "bgsu.joinhandshake.com",
  "Binghamton University": "binghamton.joinhandshake.com",
  "Biola University": "biola.joinhandshake.com",
  "Bishop College": "bishop.joinhandshake.com",
  "Bob Jones University": "bju.joinhandshake.com",
  "Bloomsburg University": "bloomu.joinhandshake.com",
  "Borough of Manhattan Community College": "bmcc.joinhandshake.com",
  "Boise State University": "boisestate.joinhandshake.com",
  "Bowdoin College": "bowdoin.joinhandshake.com",
  "Bowie State University": "bowiestate.joinhandshake.com",
  "SUNY Brockport": "brockport.joinhandshake.com",
  "Brookdale Community College": "brookdale.joinhandshake.com",
  "Brooklyn College": "brooklyn.joinhandshake.com",
  "Brown University": "brown.joinhandshake.com",
  "Bryant University": "bryant.joinhandshake.com",
  "Bryn Mawr College": "brynmawr.joinhandshake.com",
  "Ball State University": "bsu.joinhandshake.com",
  "Boston University": "bu.joinhandshake.com",
  "Bucknell University": "bucknell.joinhandshake.com",
  "University at Buffalo": "buffalo.joinhandshake.com",
  "Butler University": "butler.joinhandshake.com",
  "Baldwin Wallace University": "bw.joinhandshake.com",
  "BYU": "byu.joinhandshake.com",
  "BYU Hawaii": "byuh.joinhandshake.com",
  "BYU Idaho": "byui.joinhandshake.com",
  "Cabrini University": "cabrini.joinhandshake.com",
  "California Baptist University": "calbaptist.joinhandshake.com",
  "Cal Lutheran University": "callutheran.joinhandshake.com",
  "Cal Poly SLO": "calpoly.joinhandshake.com",
  "Cal State LA": "calstatela.joinhandshake.com",
  "California University of Pennsylvania": "calu.joinhandshake.com",
  "Calvin University": "calvin.joinhandshake.com",
  "SUNY Canton": "canton.joinhandshake.com",
  "Capital University": "capital.joinhandshake.com",
  "Carleton College": "carleton.joinhandshake.com",
  "Carlow University": "carlow.joinhandshake.com",
  "Case Western Reserve University": "case.joinhandshake.com",
  "Catholic University": "catholic.joinhandshake.com",
  "Clark Atlanta University": "cau.joinhandshake.com",
  "Cumberland County College": "cccnj.joinhandshake.com",
  "County College of Morris": "ccm.joinhandshake.com",
  "City College of New York": "ccny.joinhandshake.com",
  "Community College of Philadelphia": "ccp.joinhandshake.com",
  "Central Connecticut State": "ccsu.joinhandshake.com",
  "Cedarville University": "cedarville.joinhandshake.com",
  "Chapman University": "chapman.joinhandshake.com",
  "Chatham University": "chatham.joinhandshake.com",
  "Chestnut Hill College": "chc.joinhandshake.com",
  "Cheyney University": "cheyney.joinhandshake.com",
  "The Citadel": "citadel.joinhandshake.com",
  "Claflin University": "claflin.joinhandshake.com",
  "Clarion University": "clarion.joinhandshake.com",
  "Clarkson University": "clarkson.joinhandshake.com",
  "Clemson University": "clemson.joinhandshake.com",
  "Claremont McKenna College": "cmc.joinhandshake.com",
  "Central Michigan University": "cmich.joinhandshake.com",
  "Carnegie Mellon University": "cmu.joinhandshake.com",
  "Coastal Carolina University": "coastal.joinhandshake.com",
  "SUNY Cobleskill": "cobleskill.joinhandshake.com",
  "College of Charleston": "cofc.joinhandshake.com",
  "Colby College": "colby.joinhandshake.com",
  "Colgate University": "colgate.joinhandshake.com",
  "University of Colorado Boulder": "colorado.joinhandshake.com",
  "Colorado College": "coloradocollege.joinhandshake.com",
  "Colorado State University": "colostate.joinhandshake.com",
  "Columbia University": "columbia.joinhandshake.com",
  "Columbus State University": "columbusstate.joinhandshake.com",
  "Connecticut College": "conncoll.joinhandshake.com",
  "Bethune-Cookman University": "cookman.joinhandshake.com",
  "Cooper Union": "cooper.joinhandshake.com",
  "Coppin State University": "coppin.joinhandshake.com",
  "Cornell University": "cornell.joinhandshake.com",
  "Cornerstone University": "cornerstone.joinhandshake.com",
  "SUNY Cortland": "cortland.joinhandshake.com",
  "Cal Poly Pomona": "cpp.joinhandshake.com",
  "Creighton University": "creighton.joinhandshake.com",
  "Chadron State College": "csc.joinhandshake.com",
  "College of Staten Island": "csi.joinhandshake.com",
  "Cal State Bakersfield": "csub.joinhandshake.com",
  "Cal State Chico": "csuchico.joinhandshake.com",
  "Cal State Channel Islands": "csuci.joinhandshake.com",
  "Cal State Dominguez Hills": "csudh.joinhandshake.com",
  "Cal State East Bay": "csueastbay.joinhandshake.com",
  "Cal State Long Beach": "csulb.joinhandshake.com",
  "Cal State Maritime": "csum.joinhandshake.com",
  "Cal State Monterey Bay": "csumb.joinhandshake.com",
  "Cal State Northridge": "csun.joinhandshake.com",
  "Cleveland State University": "csuohio.joinhandshake.com",
  "Cal State Sacramento": "csus.joinhandshake.com",
  "Cal State San Bernardino": "csusb.joinhandshake.com",
  "Cal State San Marcos": "csusm.joinhandshake.com",
  "Cal State Stanislaus": "csustan.joinhandshake.com",
  "Central Washington University": "cwu.joinhandshake.com",
  "Dartmouth College": "dartmouth.joinhandshake.com",
  "Davidson College": "davidson.joinhandshake.com",
  "Defiance College": "defiance.joinhandshake.com",
  "SUNY Delhi": "delhi.joinhandshake.com",
  "Denison University": "denison.joinhandshake.com",
  "DePaul University": "depaul.joinhandshake.com",
  "DePauw University": "depauw.joinhandshake.com",
  "Delaware State University": "desu.joinhandshake.com",
  "Dickinson College": "dickinson.joinhandshake.com",
  "Dickinson State University": "dickinsonstate.joinhandshake.com",
  "Dillard University": "dillard.joinhandshake.com",
  "Dixie State University": "dixiestate.joinhandshake.com",
  "Dominican University California": "dominican.joinhandshake.com",
  "Drake University": "drake.joinhandshake.com",
  "Drexel University": "drexel.joinhandshake.com",
  "University of Denver": "du.joinhandshake.com",
  "Duke University": "duke.joinhandshake.com",
  "Duquesne University": "duq.joinhandshake.com",
  "Dakota Wesleyan University": "dwu.joinhandshake.com",
  "Earlham College": "earlham.joinhandshake.com",
  "Elizabeth City State University": "ecsu.joinhandshake.com",
  "East Carolina University": "ecu.joinhandshake.com",
  "Edinboro University": "edinboro.joinhandshake.com",
  "Elon University": "elon.joinhandshake.com",
  "Eastern Michigan University": "emich.joinhandshake.com",
  "Emory University": "emory.joinhandshake.com",
  "Eastern New Mexico University": "enmu.joinhandshake.com",
  "Eastern Oregon University": "eou.joinhandshake.com",
  "Embry-Riddle Aeronautical University": "erau.joinhandshake.com",
  "SUNY ESF": "esf.joinhandshake.com",
  "Essex County College": "essex.joinhandshake.com",
  "East Stroudsburg University": "esu.joinhandshake.com",
  "Eastern Washington University": "ewu.joinhandshake.com",
  "Fairfield University": "fairfield.joinhandshake.com",
  "Franklin & Marshall College": "fandm.joinhandshake.com",
  "Farmingdale State College": "farmingdale.joinhandshake.com",
  "Florida Atlantic University": "fau.joinhandshake.com",
  "Ferris State University": "ferris.joinhandshake.com",
  "University of Findlay": "findlay.joinhandshake.com",
  "Fisk University": "fisk.joinhandshake.com",
  "Florida International University": "fiu.joinhandshake.com",
  "Francis Marion University": "fmarion.joinhandshake.com",
  "Florida Memorial University": "fmuniv.joinhandshake.com",
  "Fordham University": "fordham.joinhandshake.com",
  "St. Francis University": "francis.joinhandshake.com",
  "Franciscan University of Steubenville": "franciscan.joinhandshake.com",
  "Frederick Community College": "frederick.joinhandshake.com",
  "SUNY Fredonia": "fredonia.joinhandshake.com",
  "Cal State Fresno": "fresnostate.joinhandshake.com",
  "Frostburg State University": "frostburg.joinhandshake.com",
  "Florida State University": "fsu.joinhandshake.com",
  "Cal State Fullerton": "fullerton.joinhandshake.com",
  "Furman University": "furman.joinhandshake.com",
  "Fort Valley State University": "fvsu.joinhandshake.com",
  "Gallaudet University": "gallaudet.joinhandshake.com",
  "Gannon University": "gannon.joinhandshake.com",
  "Georgia Tech": "gatech.joinhandshake.com",
  "Gloucester County College": "gc.joinhandshake.com",
  "Grand Canyon University": "gcu.joinhandshake.com",
  "SUNY Geneseo": "geneseo.joinhandshake.com",
  "George Fox University": "georgefox.joinhandshake.com",
  "Georgetown University": "georgetown.joinhandshake.com",
  "Georgia Southern University": "georgiasouthern.joinhandshake.com",
  "Gettysburg College": "gettysburg.joinhandshake.com",
  "George Mason University": "gmu.joinhandshake.com",
  "Gonzaga University": "gonzaga.joinhandshake.com",
  "Goshen College": "goshen.joinhandshake.com",
  "Grambling State University": "gram.joinhandshake.com",
  "Grinnell College": "grinnell.joinhandshake.com",
  "Georgia State University": "gsu.joinhandshake.com",
  "Guilford College": "guilford.joinhandshake.com",
  "Grand Valley State University": "gvsu.joinhandshake.com",
  "George Washington University": "gwu.joinhandshake.com",
  "Hamilton College": "hamilton.joinhandshake.com",
  "Hamline University": "hamline.joinhandshake.com",
  "Hampton University": "hamptonu.joinhandshake.com",
  "Hanover College": "hanover.joinhandshake.com",
  "University of Hartford": "hartford.joinhandshake.com",
  "Hartwick College": "hartwick.joinhandshake.com",
  "Harvard University": "harvard.joinhandshake.com",
  "Haverford College": "haverford.joinhandshake.com",
  "University of Hawaii": "hawaii.joinhandshake.com",
  "Houston Baptist University": "hbu.joinhandshake.com",
  "Hudson County Community College": "hccc.joinhandshake.com",
  "Heidelberg University": "heidelberg.joinhandshake.com",
  "High Point University": "highpoint.joinhandshake.com",
  "Hillsdale College": "hillsdale.joinhandshake.com",
  "Hiram College": "hiram.joinhandshake.com",
  "Harvey Mudd College": "hmc.joinhandshake.com",
  "Holy Names University": "hnu.joinhandshake.com",
  "Hofstra University": "hofstra.joinhandshake.com",
  "Hope College": "hope.joinhandshake.com",
  "Hostos Community College": "hostos.joinhandshake.com",
  "Howard University": "howard.joinhandshake.com",
  "Hawaii Pacific University": "hpu.joinhandshake.com",
  "Harris-Stowe State University": "hssu.joinhandshake.com",
  "Hardin-Simmons University": "hsutx.joinhandshake.com",
  "Huston-Tillotson University": "htu.joinhandshake.com",
  "Hunter College": "hunter.joinhandshake.com",
  "Husson University": "husson.joinhandshake.com",
  "Iowa State University": "iastate.joinhandshake.com",
  "Illinois Institute of Technology": "iit.joinhandshake.com",
  "University of Illinois Urbana-Champaign": "illinois.joinhandshake.com",
  "Immaculata University": "immaculata.joinhandshake.com",
  "Indiana University": "indiana.joinhandshake.com",
  "Indiana State University": "indstate.joinhandshake.com",
  "University of Iowa": "iowa.joinhandshake.com",
  "Idaho State University": "isu.joinhandshake.com",
  "Indiana University of Pennsylvania": "iup.joinhandshake.com",
  "Indiana University\u2013Purdue University Indianapolis": "iupui.joinhandshake.com",
  "Jarvis Christian University": "jarvis.joinhandshake.com",
  "John Carroll University": "jcu.joinhandshake.com",
  "William Jessup University": "jessup.joinhandshake.com",
  "John Jay College": "jjay.joinhandshake.com",
  "James Madison University": "jmu.joinhandshake.com",
  "Jacksonville State University": "jsu.joinhandshake.com",
  "Jackson State University": "jsums.joinhandshake.com",
  "Jacksonville University": "ju.joinhandshake.com",
  "Johnson & Wales University": "jwu.joinhandshake.com",
  "Kingsborough Community College": "kbcc.joinhandshake.com",
  "Keene State College": "keene.joinhandshake.com",
  "Kennesaw State University": "kennesaw.joinhandshake.com",
  "Kent State University": "kent.joinhandshake.com",
  "Kenyon College": "kenyon.joinhandshake.com",
  "Kettering University": "kettering.joinhandshake.com",
  "Kansas State University": "kstate.joinhandshake.com",
  "University of Kansas": "ku.joinhandshake.com",
  "Kutztown University": "kutztown.joinhandshake.com",
  "Kalamazoo College": "kzoo.joinhandshake.com",
  "LaGuardia Community College": "lagcc.joinhandshake.com",
  "Lamar University": "lamar.joinhandshake.com",
  "Lander University": "lander.joinhandshake.com",
  "Lane College": "lanecollege.joinhandshake.com",
  "Langston University": "langston.joinhandshake.com",
  "La Salle University": "lasalle.joinhandshake.com",
  "La Sierra University": "lasierra.joinhandshake.com",
  "Lewis & Clark College": "lclark.joinhandshake.com",
  "LDSBC": "ldsbc.joinhandshake.com",
  "Lehigh University": "lehigh.joinhandshake.com",
  "Lehman College": "lehman.joinhandshake.com",
  "Le Moyne College": "lemoyne.joinhandshake.com",
  "Liberty University": "liberty.joinhandshake.com",
  "Lincoln University Pennsylvania": "lincoln.joinhandshake.com",
  "Lincoln University Missouri": "lincolnu.joinhandshake.com",
  "Linfield University": "linfield.joinhandshake.com",
  "Lipscomb University": "lipscomb.joinhandshake.com",
  "Long Island University": "liu.joinhandshake.com",
  "Livingstone College": "livingstone.joinhandshake.com",
  "Loyola Marymount University": "lmu.joinhandshake.com",
  "LeMoyne-Owen College": "loc.joinhandshake.com",
  "Lock Haven University": "lockhaven.joinhandshake.com",
  "Lone Star College": "lonestar.joinhandshake.com",
  "Loras College": "loras.joinhandshake.com",
  "Loyola University Maryland": "loyola.joinhandshake.com",
  "Lake Superior State University": "lssu.joinhandshake.com",
  "Louisiana State University": "lsu.joinhandshake.com",
  "Lawrence Technological University": "ltu.joinhandshake.com",
  "Loyola University Chicago": "luc.joinhandshake.com",
  "Luther College": "luther.joinhandshake.com",
  "Macalester College": "macalester.joinhandshake.com",
  "University of Maine": "maine.joinhandshake.com",
  "Manchester University": "manchester.joinhandshake.com",
  "Mansfield University": "mansfield.joinhandshake.com",
  "Maricopa Community Colleges": "maricopa.joinhandshake.com",
  "Marietta College": "marietta.joinhandshake.com",
  "Marist College": "marist.joinhandshake.com",
  "Marquette University": "marquette.joinhandshake.com",
  "Marymount University": "marymount.joinhandshake.com",
  "Milwaukee Area Technical College": "matc.joinhandshake.com",
  "Mercer County Community College": "mccc.joinhandshake.com",
  "McMurry University": "mcm.joinhandshake.com",
  "Medgar Evers College": "mec.joinhandshake.com",
  "Menlo College": "menlo.joinhandshake.com",
  "Mercer University": "mercer.joinhandshake.com",
  "Mercyhurst University": "mercyhurst.joinhandshake.com",
  "University of Miami": "miami.joinhandshake.com",
  "Miami University Ohio": "miamioh.joinhandshake.com",
  "Middlebury College": "middlebury.joinhandshake.com",
  "Middlesex College NJ": "middlesexcc.joinhandshake.com",
  "Miles College": "miles.joinhandshake.com",
  "Millersville University": "millersville.joinhandshake.com",
  "Millsaps College": "millsaps.joinhandshake.com",
  "Colorado School of Mines": "mines.joinhandshake.com",
  "Minot State University": "minotstate.joinhandshake.com",
  "University of Missouri": "missouri.joinhandshake.com",
  "Missouri State University": "missouristate.joinhandshake.com",
  "MIT": "mit.joinhandshake.com",
  "Meharry Medical College": "mmc.joinhandshake.com",
  "Montana State University": "montana.joinhandshake.com",
  "Morehouse College": "morehouse.joinhandshake.com",
  "Morgan State University": "morgan.joinhandshake.com",
  "Morris College": "morris.joinhandshake.com",
  "SUNY Morrisville": "morrisville.joinhandshake.com",
  "Mount Union College": "mountunion.joinhandshake.com",
  "Mississippi State University": "msstate.joinhandshake.com",
  "Missouri University of Science and Technology": "mst.joinhandshake.com",
  "Michigan State University": "msu.joinhandshake.com",
  "Metropolitan State University of Denver": "msudenver.joinhandshake.com",
  "Midwestern State University": "msutexas.joinhandshake.com",
  "Muhlenberg College": "muhlenberg.joinhandshake.com",
  "Muskingum University": "muskingum.joinhandshake.com",
  "Mississippi Valley State University": "mvsu.joinhandshake.com",
  "Northern Arizona University": "nau.joinhandshake.com",
  "North Carolina A&T": "ncat.joinhandshake.com",
  "North Carolina Central University": "nccu.joinhandshake.com",
  "NC State University": "ncsu.joinhandshake.com",
  "University of Notre Dame": "nd.joinhandshake.com",
  "Notre Dame College Ohio": "ndc.joinhandshake.com",
  "Notre Dame de Namur University": "ndnu.joinhandshake.com",
  "North Dakota State University": "ndsu.joinhandshake.com",
  "Neumann University": "neumann.joinhandshake.com",
  "University of New Haven": "newhaven.joinhandshake.com",
  "SUNY New Paltz": "newpaltz.joinhandshake.com",
  "The New School": "newschool.joinhandshake.com",
  "New Jersey Institute of Technology": "njit.joinhandshake.com",
  "New Mexico State University": "nmsu.joinhandshake.com",
  "New Mexico Tech": "nmt.joinhandshake.com",
  "Northern Michigan University": "nmu.joinhandshake.com",
  "Northeastern University": "northeastern.joinhandshake.com",
  "Northwestern University": "northwestern.joinhandshake.com",
  "Northwood University": "northwood.joinhandshake.com",
  "Nevada State College": "nsc.joinhandshake.com",
  "Norfolk State University": "nsu.joinhandshake.com",
  "Northern Virginia Community College": "nvcc.joinhandshake.com",
  "New York University": "nyu.joinhandshake.com",
  "Oakland University": "oakland.joinhandshake.com",
  "Oberlin College": "oberlin.joinhandshake.com",
  "Ocean County College": "ocean.joinhandshake.com",
  "Old Dominion University": "odu.joinhandshake.com",
  "Ohio University": "ohio.joinhandshake.com",
  "Ohio Dominican University": "ohiodominican.joinhandshake.com",
  "Oklahoma State University": "okstate.joinhandshake.com",
  "SUNY Old Westbury": "oldwestbury.joinhandshake.com",
  "University of Mississippi": "olemiss.joinhandshake.com",
  "Olivet College": "olivet.joinhandshake.com",
  "SUNY Oneonta": "oneonta.joinhandshake.com",
  "Ohio Northern University": "onu.joinhandshake.com",
  "Oregon State University": "oregonstate.joinhandshake.com",
  "Ohio State University": "osu.joinhandshake.com",
  "SUNY Oswego": "oswego.joinhandshake.com",
  "Otterbein University": "otterbein.joinhandshake.com",
  "University of Oklahoma": "ou.joinhandshake.com",
  "Ohio Wesleyan University": "owu.joinhandshake.com",
  "Occidental College": "oxy.joinhandshake.com",
  "Pace University": "pace.joinhandshake.com",
  "University of Pacific": "pacific.joinhandshake.com",
  "Pacific University": "pacificu.joinhandshake.com",
  "Paine College": "paine.joinhandshake.com",
  "Parsons School of Design": "parsons.joinhandshake.com",
  "Passaic County Community College": "pccc.joinhandshake.com",
  "Portland State University": "pdx.joinhandshake.com",
  "Pennsylvania Western University": "pennwest.joinhandshake.com",
  "Pepperdine University": "pepperdine.joinhandshake.com",
  "Peru State College": "peru.joinhandshake.com",
  "Philander Smith College": "philandersmith.joinhandshake.com",
  "Pima Community College": "pima.joinhandshake.com",
  "University of Pittsburgh": "pitt.joinhandshake.com",
  "Pitzer College": "pitzer.joinhandshake.com",
  "SUNY Plattsburgh": "plattsburgh.joinhandshake.com",
  "Pacific Lutheran University": "plu.joinhandshake.com",
  "Plymouth State University": "plymouth.joinhandshake.com",
  "Point Loma Nazarene University": "pointloma.joinhandshake.com",
  "Point Park University": "pointpark.joinhandshake.com",
  "Pomona College": "pomona.joinhandshake.com",
  "Post University": "post.joinhandshake.com",
  "SUNY Potsdam": "potsdam.joinhandshake.com",
  "Paul Quinn College": "pqc.joinhandshake.com",
  "Pratt Institute": "pratt.joinhandshake.com",
  "Presbyterian College": "presby.joinhandshake.com",
  "Princeton University": "princeton.joinhandshake.com",
  "Providence College": "providence.joinhandshake.com",
  "Penn State University": "psu.joinhandshake.com",
  "Pacific Union College": "puc.joinhandshake.com",
  "University of Puget Sound": "pugetsound.joinhandshake.com",
  "SUNY Purchase": "purchase.joinhandshake.com",
  "Purdue University": "purdue.joinhandshake.com",
  "Prairie View A&M University": "pvamu.joinhandshake.com",
  "Queens College": "qc.joinhandshake.com",
  "Queensborough Community College": "qcc.joinhandshake.com",
  "Quinnipiac University": "quinnipiac.joinhandshake.com",
  "Reading Area Community College": "racc.joinhandshake.com",
  "Radford University": "radford.joinhandshake.com",
  "Raritan Valley Community College": "raritanval.joinhandshake.com",
  "University of Redlands": "redlands.joinhandshake.com",
  "Reed College": "reed.joinhandshake.com",
  "Regent University": "regent.joinhandshake.com",
  "Regis University": "regis.joinhandshake.com",
  "Rhodes College": "rhodes.joinhandshake.com",
  "Rice University": "rice.joinhandshake.com",
  "Richland College": "richlandcollege.joinhandshake.com",
  "Rochester Institute of Technology": "rit.joinhandshake.com",
  "Robert Morris University": "rmu.joinhandshake.com",
  "Rockhurst University": "rockhurst.joinhandshake.com",
  "Rollins College": "rollins.joinhandshake.com",
  "Rose-Hulman Institute of Technology": "rose-hulman.joinhandshake.com",
  "Rowan College": "rowancollege.joinhandshake.com",
  "Rensselaer Polytechnic Institute": "rpi.joinhandshake.com",
  "Rust College": "rustcollege.joinhandshake.com",
  "Rutgers University": "rutgers.joinhandshake.com",
  "Roger Williams University": "rwu.joinhandshake.com",
  "Sacred Heart University": "sacredheart.joinhandshake.com",
  "Salem Community College": "salemcc.joinhandshake.com",
  "Salisbury University": "salisbury.joinhandshake.com",
  "Salve Regina University": "salve.joinhandshake.com",
  "Samford University": "samford.joinhandshake.com",
  "University of San Diego": "sandiego.joinhandshake.com",
  "San Jacinto College": "sanjacinto.joinhandshake.com",
  "Savannah State University": "savannahstate.joinhandshake.com",
  "University of South Carolina": "sc.joinhandshake.com",
  "Scripps College": "scrippscollege.joinhandshake.com",
  "South Carolina State University": "scsu.joinhandshake.com",
  "Santa Clara University": "scu.joinhandshake.com",
  "San Diego Christian College": "sdcc.joinhandshake.com",
  "South Dakota State University": "sdstate.joinhandshake.com",
  "San Diego State University": "sdsu.joinhandshake.com",
  "Seattle University": "seattleu.joinhandshake.com",
  "Sewanee": "sewanee.joinhandshake.com",
  "Stephen F. Austin State University": "sfasu.joinhandshake.com",
  "Shaw University": "shawu.joinhandshake.com",
  "Shippensburg University": "ship.joinhandshake.com",
  "Sam Houston State University": "shsu.joinhandshake.com",
  "Siena College": "siena.joinhandshake.com",
  "Simpson University": "simpsonu.joinhandshake.com",
  "San Jose State University": "sjsu.joinhandshake.com",
  "Saint Joseph's University": "sju.joinhandshake.com",
  "Skidmore College": "skidmore.joinhandshake.com",
  "Sarah Lawrence College": "slc.joinhandshake.com",
  "Saint Louis University": "slu.joinhandshake.com",
  "Saint Michael's College": "smcvt.joinhandshake.com",
  "St. Norbert College": "snc.joinhandshake.com",
  "Southern New Hampshire University": "snhu.joinhandshake.com",
  "Snow College": "snow.joinhandshake.com",
  "Southern Connecticut State": "southernct.joinhandshake.com",
  "South Texas College": "southtexascollege.joinhandshake.com",
  "Spelman College": "spelman.joinhandshake.com",
  "Seattle Pacific University": "spu.joinhandshake.com",
  "Slippery Rock University": "sru.joinhandshake.com",
  "St. Augustine's University": "st-aug.joinhandshake.com",
  "Stanford University": "stanford.joinhandshake.com",
  "Stetson University": "stetson.joinhandshake.com",
  "Stevens Institute of Technology": "stevens.joinhandshake.com",
  "Stillman College": "stillman.joinhandshake.com",
  "St. John's University": "stjohns.joinhandshake.com",
  "St. Catherine University": "stkate.joinhandshake.com",
  "Saint Mary's College of California": "stmarys-ca.joinhandshake.com",
  "St. Olaf College": "stolaf.joinhandshake.com",
  "Stony Brook University": "stonybrook.joinhandshake.com",
  "Southern University": "subr.joinhandshake.com",
  "Sul Ross State University": "sulross.joinhandshake.com",
  "Southern University New Orleans": "suno.joinhandshake.com",
  "SUNY Poly": "sunypoly.joinhandshake.com",
  "Southern University Shreveport": "susla.joinhandshake.com",
  "Sussex County Community College": "sussex.joinhandshake.com",
  "Southern Utah University": "suu.joinhandshake.com",
  "Saginaw Valley State University": "svsu.joinhandshake.com",
  "Swarthmore College": "swarthmore.joinhandshake.com",
  "Southwestern Christian College": "swcc.joinhandshake.com",
  "Syracuse University": "syr.joinhandshake.com",
  "Talladega College": "talladega.joinhandshake.com",
  "Texas A&M University": "tamu.joinhandshake.com",
  "Texas A&M Commerce": "tamuc.joinhandshake.com",
  "Tarleton State University": "tarleton.joinhandshake.com",
  "Taylor University": "taylor.joinhandshake.com",
  "Texas Christian University": "tcu.joinhandshake.com",
  "Temple University": "temple.joinhandshake.com",
  "Texas College": "texascollege.joinhandshake.com",
  "Thomas Aquinas College": "thomasaquinas.joinhandshake.com",
  "Tiffin University": "tiffin.joinhandshake.com",
  "Tennessee State University": "tnstate.joinhandshake.com",
  "Tougaloo College": "tougaloo.joinhandshake.com",
  "Towson University": "towson.joinhandshake.com",
  "Trinity College": "trincoll.joinhandshake.com",
  "Troy University": "troy.joinhandshake.com",
  "Truman State University": "truman.joinhandshake.com",
  "Texas Southern University": "tsu.joinhandshake.com",
  "Texas Tech University": "ttu.joinhandshake.com",
  "Tufts University": "tufts.joinhandshake.com",
  "Tulane University": "tulane.joinhandshake.com",
  "Tuskegee University": "tuskegee.joinhandshake.com",
  "Texas Woman's University": "twu.joinhandshake.com",
  "Texas State University": "txstate.joinhandshake.com",
  "University of Alabama": "ua.joinhandshake.com",
  "University of Alaska Anchorage": "uaa.joinhandshake.com",
  "University of Alaska Fairbanks": "uaf.joinhandshake.com",
  "University of Arkansas at Pine Bluff": "uapb.joinhandshake.com",
  "University of Arkansas": "uark.joinhandshake.com",
  "University of Cincinnati": "uc.joinhandshake.com",
  "Union County College": "ucc.joinhandshake.com",
  "UC Davis": "ucdavis.joinhandshake.com",
  "University of Central Florida": "ucf.joinhandshake.com",
  "UC Hastings": "uchastings.joinhandshake.com",
  "University of Chicago": "uchicago.joinhandshake.com",
  "UC Irvine": "uci.joinhandshake.com",
  "UCLA": "ucla.joinhandshake.com",
  "UC Merced": "ucmerced.joinhandshake.com",
  "University of Connecticut": "uconn.joinhandshake.com",
  "UC Riverside": "ucr.joinhandshake.com",
  "UC Santa Barbara": "ucsb.joinhandshake.com",
  "UC Santa Cruz": "ucsc.joinhandshake.com",
  "UC San Diego": "ucsd.joinhandshake.com",
  "University of Dayton": "udayton.joinhandshake.com",
  "University of Florida": "ufl.joinhandshake.com",
  "University of Georgia": "uga.joinhandshake.com",
  "University of Houston": "uh.joinhandshake.com",
  "University of Houston Downtown": "uhd.joinhandshake.com",
  "University of Idaho": "uidaho.joinhandshake.com",
  "University of Kentucky": "uky.joinhandshake.com",
  "University of Massachusetts Amherst": "umass.joinhandshake.com",
  "UMBC": "umbc.joinhandshake.com",
  "University of Maryland": "umd.joinhandshake.com",
  "University of Michigan Dearborn": "umdearborn.joinhandshake.com",
  "University of Maryland Eastern Shore": "umes.joinhandshake.com",
  "University of Michigan Flint": "umflint.joinhandshake.com",
  "University of Michigan": "umich.joinhandshake.com",
  "University of Missouri Kansas City": "umkc.joinhandshake.com",
  "University of Minnesota": "umn.joinhandshake.com",
  "University of Missouri St. Louis": "umsl.joinhandshake.com",
  "University of Montana": "umt.joinhandshake.com",
  "University of North Carolina": "unc.joinhandshake.com",
  "UNC Charlotte": "uncc.joinhandshake.com",
  "Fayetteville State University": "uncfsu.joinhandshake.com",
  "UNC Greensboro": "uncg.joinhandshake.com",
  "University of Northern Colorado": "unco.joinhandshake.com",
  "University of North Dakota": "und.joinhandshake.com",
  "North Georgia College": "ung.joinhandshake.com",
  "University of New Hampshire": "unh.joinhandshake.com",
  "University of Northern Iowa": "uni.joinhandshake.com",
  "Union College": "union.joinhandshake.com",
  "University of Nebraska Kearney": "unk.joinhandshake.com",
  "University of Nebraska Lincoln": "unl.joinhandshake.com",
  "University of Nevada Las Vegas": "unlv.joinhandshake.com",
  "University of New Mexico": "unm.joinhandshake.com",
  "University of Nebraska Omaha": "unomaha.joinhandshake.com",
  "University of Nevada Reno": "unr.joinhandshake.com",
  "University of North Texas": "unt.joinhandshake.com",
  "University of Oregon": "uoregon.joinhandshake.com",
  "University of Portland": "up.joinhandshake.com",
  "University of Pennsylvania": "upenn.joinhandshake.com",
  "University of Rhode Island": "uri.joinhandshake.com",
  "Ursinus College": "ursinus.joinhandshake.com",
  "Ursuline College": "ursuline.joinhandshake.com",
  "University of Southern California": "usc.joinhandshake.com",
  "University of South Dakota": "usd.joinhandshake.com",
  "University of South Florida": "usf.joinhandshake.com",
  "University of San Francisco": "usfca.joinhandshake.com",
  "University of Southern Maine": "usm.joinhandshake.com",
  "Utah State University": "usu.joinhandshake.com",
  "University of Texas Arlington": "uta.joinhandshake.com",
  "University of Utah": "utah.joinhandshake.com",
  "University of Texas Dallas": "utdallas.joinhandshake.com",
  "University of Texas El Paso": "utep.joinhandshake.com",
  "University of Texas Austin": "utexas.joinhandshake.com",
  "University of Tennessee": "utk.joinhandshake.com",
  "University of Toledo": "utoledo.joinhandshake.com",
  "University of Texas San Antonio": "utsa.joinhandshake.com",
  "University of Vermont": "uvm.joinhandshake.com",
  "Utah Valley University": "uvu.joinhandshake.com",
  "University of Washington": "uw.joinhandshake.com",
  "University of Wisconsin-Milwaukee": "uwm.joinhandshake.com",
  "University of Wyoming": "uwyo.joinhandshake.com",
  "Valparaiso University": "valpo.joinhandshake.com",
  "Vanderbilt University": "vanderbilt.joinhandshake.com",
  "Vanguard University": "vanguard.joinhandshake.com",
  "Vassar College": "vassar.joinhandshake.com",
  "Virginia Commonwealth University": "vcu.joinhandshake.com",
  "Villanova University": "villanova.joinhandshake.com",
  "University of Virginia": "virginia.joinhandshake.com",
  "Virginia State University": "vsu.joinhandshake.com",
  "Virginia Tech": "vt.joinhandshake.com",
  "Virginia Union University": "vuu.joinhandshake.com",
  "Wabash College": "wabash.joinhandshake.com",
  "Walla Walla University": "wallawalla.joinhandshake.com",
  "Warren County Community College": "warren.joinhandshake.com",
  "Wartburg College": "wartburg.joinhandshake.com",
  "Wayne State University": "wayne.joinhandshake.com",
  "Waynesburg University": "waynesburg.joinhandshake.com",
  "Western Carolina University": "wcu.joinhandshake.com",
  "West Chester University": "wcupa.joinhandshake.com",
  "Weber State University": "weber.joinhandshake.com",
  "Wesleyan University": "wesleyan.joinhandshake.com",
  "Westmont College": "westmont.joinhandshake.com",
  "Wake Forest University": "wfu.joinhandshake.com",
  "Whitman College": "whitman.joinhandshake.com",
  "Whittier College": "whittier.joinhandshake.com",
  "Whitworth University": "whitworth.joinhandshake.com",
  "Widener University": "widener.joinhandshake.com",
  "Wiley College": "wiley.joinhandshake.com",
  "Willamette University": "willamette.joinhandshake.com",
  "Winthrop University": "winthrop.joinhandshake.com",
  "University of Wisconsin Madison": "wisc.joinhandshake.com",
  "Wittenberg University": "wittenberg.joinhandshake.com",
  "William & Mary": "wm.joinhandshake.com",
  "Western Michigan University": "wmich.joinhandshake.com",
  "Western New Mexico University": "wnmu.joinhandshake.com",
  "Wofford College": "wofford.joinhandshake.com",
  "College of Wooster": "wooster.joinhandshake.com",
  "Western Oregon University": "wou.joinhandshake.com",
  "Wayne State College": "wsc.joinhandshake.com",
  "Winston-Salem State University": "wssu.joinhandshake.com",
  "Washington State University": "wsu.joinhandshake.com",
  "West Texas A&M University": "wtamu.joinhandshake.com",
  "Washington University St. Louis": "wustl.joinhandshake.com",
  "West Virginia University": "wvu.joinhandshake.com",
  "Western Washington University": "wwu.joinhandshake.com",
  "Xavier University": "xavier.joinhandshake.com",
  "Xavier University of Louisiana": "xula.joinhandshake.com",
  "Yale University": "yale.joinhandshake.com",
  "York College": "york.joinhandshake.com",
  "Youngstown State University": "ysu.joinhandshake.com",
  "Yeshiva University": "yu.joinhandshake.com"
};
